### ISSUE TITLE
onSharedElementEnd java.lang.NullPointerException

### ISSUE THREAD

**Issue by Zhuxf1111** [yellowcath/YcShareElement#2]
java.lang.NullPointerException: Attempt to invoke virtual method 'android.os.Bundle com.hw.ycshareelement.transition.ShareElementInfo.getFromViewBundle()' on a null object reference
        at com.hw.ycshareelement.YcShareElement$2.onSharedElementEnd(YcShareElement.java:183)
        at android.app.ExitTransitionCoordinator.startSharedElementExit(ExitTransitionCoordinator.java:182)
        at android.app.ExitTransitionCoordinator.access$000(ExitTransitionCoordinator.java:49)
        at android.app.ExitTransitionCoordinator$1.run(ExitTransitionCoordinator.java:155)
        at android.app.ActivityTransitionCoordinator.startTransition(ActivityTransitionCoordinator.java:837)
        at android.app.ExitTransitionCoordinator.sharedElementExitBack(ExitTransitionCoordinator.java:153)
        at android.app.ExitTransitionCoordinator.onReceiveResult(ExitTransitionCoordinator.java:106)
        at android.os.ResultReceiver$MyRunnable.run(ResultReceiver.java:50)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6649)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:826)

**Comment by Zhuxf1111** [comment]
ActivityB内viewpager滑动变换后， 返回时会抛出空指针

**Comment by yellowcath** [comment]
加了个判断
implementation 'com.github.yellowcath:YcShareElement:1.3.1'
不过你这个一般是做返回动画的时候Activity B的View有了变动，如果还有问题的话，最好能提供下出问题的场景

**Comment by Zhuxf1111** [comment]
不会crash了 但是返回时的动画没有了

**Comment by Zhuxf1111** [comment]
我把列表内所有的view都传过去就都可以了  但是demo中又是好的

**Comment by yellowcath** [comment]
你看看是不是返回同时调了notifyDataSetChanged之类的函数。

**Comment by Zhuxf1111** [comment]
没有 我的列表就只有几个item 也不是放在recyclerview里面的 和这个有关吗？

**Comment by yellowcath** [comment]
没有具体代码我这里不好判断，给你个建议，在我的demo上一步步改造成你出问题的页面，一直改到出问题为止，这样就能判断是哪里出bug了

**Comment by Loner111** [comment]
这个问题我也遇到过，我是在这样的一个场景“A activity是一个recycleView，B activity是具体的详情页，当点击A activity里的item进入B activity时，快速点击两个item（由于执行动画会有一定的延时，可以在第一个item执行动画的时候点击第二个item），这时进入B activity后再返回就出现这个问题”
