### ISSUE TITLE
YcShareElement.enableContentTransition()导致异常

### ISSUE THREAD

**Issue by Vanish136** [yellowcath/YcShareElement#3]
调用YcShareElement.enableContentTransition()会导致如下异常：
```
android.util.AndroidRuntimeException: requestFeature() must be called before adding content
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3300)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3484)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:86)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2123)
        at android.os.Handler.dispatchMessage(Handler.java:109)
        at android.os.Looper.loop(Looper.java:207)
        at android.app.ActivityThread.main(ActivityThread.java:7470)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)
     Caused by: android.util.AndroidRuntimeException: requestFeature() must be called before adding content
        at com.android.internal.policy.PhoneWindow.requestFeature(PhoneWindow.java:385)
```

看了下实现，是对Application对象注册ActivityLifecycleCallbacks回调，在所有Activity的onCreate()后设置activity.getWindow().requestFeature(Window.FEATURE_CONTENT_TRANSITIONS);
实际上在onCreate后Activity添加了ContentView后是不能再设置其Window对象的requestFeature()，所以请作者修复一下啦

**Comment by yellowcath** [comment]
这样写是没问题的：
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
    }

这样写是有问题的：
    protected void onCreate(Bundle savedInstanceState) {
        setContentView(R.layout.activity_main);
        super.onCreate(savedInstanceState);
       
    }
因为ActivityLifecycleCallbacks的回调是在super.onCreate里面
